config.set('fonts.default_size', '18pt')
config.set('colors.completion.even.bg', '#000000')
config.set('colors.completion.odd.bg', '#111111')
config.set('colors.completion.item.selected.bg', '#ffffff')
config.set('colors.completion.even.bg', '#000000')
config.set('colors.tabs.even.bg', '#000000')
config.set('colors.tabs.odd.bg', '#000000')
config.set('colors.tabs.selected.even.bg', '#ffffff')
config.set('colors.tabs.selected.odd.bg', '#ffffff')
config.set('colors.tabs.selected.even.fg', '#000000')
config.set('colors.tabs.selected.odd.fg', '#000000')
config.set('tabs.padding', {"bottom": 8, "left": 2, "right": 0, "top": 8})
config.set('tabs.indicator.padding', {"bottom": 0, "left": 0, "right": 4, "top": 0})
config.set('downloads.location.directory', '~/')
config.set('downloads.location.suggestion', 'both')
config.set('downloads.position', 'bottom')
config.set('downloads.position', 'bottom')
config.set('input.insert_mode.auto_load', False)
config.set('tabs.last_close', 'close')
config.set('url.searchengines', {"DEFAULT": "https://www.google.com/search?q={}"})
config.set('tabs.indicator.width', 0)
config.set('completion.open_categories', ["history", "bookmarks", "quickmarks"])
config.set('search.wrap', False)
config.set('window.title_format', 'qutebrowser')
config.set('content.notifications', False)
config.set('zoom.default', '150%')

config.unbind('<ctrl-v>', mode='normal')
config.unbind('u', mode='normal')
config.unbind('q', mode='normal')
config.unbind('r', mode='normal')
config.unbind('<ctrl-Q>', mode='normal')
config.unbind('<ctrl-W>', mode='normal')
config.unbind('<ctrl-X>', mode='normal')
config.unbind('<ctrl-A>', mode='normal')
config.unbind('gr', mode='normal')

config.bind('<ctrl-tab>', 'tab-next')
config.bind('<ctrl-shift-tab>', 'tab-prev')
config.bind('<ctrl-r>', 'config-source')
config.bind('<ctrl-h>', 'history')
config.bind('<ctrl-alt-left>', 'tab-move -')
config.bind('<ctrl-alt-right>', 'tab-move +')
config.bind('<alt-left>', 'back')
config.bind('<alt-right>', 'forward')
config.bind('<ctrl-p>', 'set content.private_browsing true')
config.bind('<ctrl-o>', 'set content.private_browsing false')
config.bind('d', 'record-macro')
config.bind('qq', 'tab-close')
config.bind('ee', 'set-cmd-text :open {url:pretty}')
config.bind('gv', 'hint links spawn streamlink {hint-url} best')

config.bind('gn', 'open https://www.netflix.com')
config.bind('gy', 'open https://www.youtube.com')
config.bind('gc', 'open https://canvas.umn.edu')
config.bind('gc', 'open https://canvas.umn.edu')
config.bind('gt', 'open https://github.com')
config.bind('gh', 'open https://www.google.com')
config.bind('gw', 'open https://web.whatsapp.com/')
config.bind('gl', 'open https://lib.rs/')
config.bind('gs1', 'open https://app.slack.com/client/TTZ6C8MGS/CUBG6JRSQ')
config.bind('gs2', 'open https://app.slack.com/client/TTUGLPPSP/CU7SBD9M5')
config.bind('grr', 'open https://doc.rust-lang.org/rust-by-example/index.html')
config.bind('grv', 'open https://doc.rust-lang.org/std/vec/struct.Vec.html')
config.bind('grs', 'open https://doc.rust-lang.org/std/slice/index.html')

config.unbind('gm', mode='normal')
config.bind('gm1', 'open https://mail.google.com/mail/u/0/#inbox')
config.bind('gm2', 'open https://mail.google.com/mail/u/1/#inbox')
config.bind('gm3', 'open https://mail.google.com/mail/u/2/#inbox')
config.bind('gm4', 'open https://mail.google.com/mail/u/3/#inbox')
