format = "▶ "
right_format = "$directory$cmd_duration$status"

add_newline = false

[status]
style = "bg:blue"
symbol = "🔴"
format = '[\[$int $symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
style = 'yellow underline'
format = '\([took $duration]($style)\) '
