format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$line_break\
$cmd_duration\
$jobs\
$status\
$shell\
$character\
"""
