#! /bin/bash

# Dependencies
# xrandr
# bc

maxBri=100
minBri=5

input=$1
delta=$1
oldBri=$(echo $(xrandr --verbose | grep -i brightness | awk 'NR==1{print $2}') \* 100 | bc -l | xargs printf "%.0f\n")
newBri=$(echo $oldBri + $delta | bc -l)

if [ $newBri -gt $maxBri ]; then
    echo Too bright screen;
    exit 1;
fi

if [ $newBri -lt $minBri ]; then
    echo Too dim screen;
    exit 1;
fi

normNewBri=$(echo $newBri / 100 | bc -l)
xrandr --output eDP-1 --brightness $normNewBri && pkill -RTMIN+1 i3blocks

