#!/bin/bash

EMOJI=$(cat $XDG_CONFIG_HOME/stupidscripts/emojis.csv | dmenu -b -l 10 -i -fn 'Fira Mono-20' -p 'Select an emoji' | awk -F "," '{print $1}' | tr -d '\n')

if [ "${EMOJI}" != "" ]; then
  xclip <(echo ${EMOJI}) -selection clipboard && pgrep dunst > /dev/null && notify-send "\"$(xclip -o -selection clipboard)\" is copied into clipboard"
fi
