#! /bin/bash

# Check if ffmpeg is already running
pgrep ffmpeg
if [ $? -eq 0 ]; then
  notify-send -a "ffmpeg" "An ffmpeg screencast is already running" -t 2000
  exit -1
fi

FILE_NAME=$(echo "" | dmenu -b -fn 'Fira Mono-20' -i -p "${1}")
[ $? -eq 0 ] || exit

FILE_PATH="$HOME/screencasts/${FILE_NAME}.mkv"
# Check if given file exists
if [ -f ${FILE_PATH} ]; then
  notify-send -a "ffmpeg" "A file with name \"${FILE_NAME}\" already exists. Try another file name" -t 2000
else
  ffmpeg -loglevel quiet -video_size 800x825 -framerate 60 -f x11grab -i :0.0+560,115 -c:v libx264 -preset ultrafast -crf 0 -threads 0 ${FILE_PATH}
  notify-send -a "ffmpeg" "Screencast saved to ${FILE_NAME}" -t 2000
fi

