#! /bin/bash

FILE_NAME=$(echo "" | dmenu -b -fn 'Fira Mono-20' -i -p "${1}")
[ $? -eq 0 ] || exit

echo ${FILE_PATH}
FILE_PATH="$HOME/screenshots/${FILE_NAME}.png"
# Check if given file exists
if [ -f ${FILE_PATH} ]; then
  notify-send -a "scrot" "A file with name \"${FILE_NAME}\" already exists. Try another file name" -t 2000
else
  scrot ${2} "$HOME/screenshots/${FILE_NAME}.png" \
  && notify-send -a "scrot" "${FILE_NAME} : ${3}" -i /usr/share/icons/Adwaita/24x24/mimetypes/image-x-generic-symbolic.symbolic.png -t 1000
fi

