#! /bin/bash

# check if input is number
TIMER_MINUTES=$(echo -e "10\n20\n" | dmenu -b -i -fn 'Fira Mono-20' -p "Timer (min)")
TIMER_SECONDS=$((TIMER_MINUTES * 60))

[ "${TIMER_SECONDS}" = "" ] && exit 0

if ! [[ "${TIMER_SECONDS}" == ?(-)+([0-9]) ]] ; then
  notify-send --app-name="Timer" --urgency=CRITICAL "Need a number :)"
  exit -1
fi

if ! ((TIMER_SECONDS >= 15 && TIMER_SECONDS <= 3600)); then
  notify-send --app-name="Timer" --urgency=CRITICAL "Out of range"
  exit -1
fi

sleep ${TIMER_SECONDS} && notify-send --app-name="Timer" --urgency=CRITICAL "${TIMER_SECONDS} seconds up"
