#! /bin/bash

# Dependencies
# xrandr
# bc

oldBri=$(echo $(xrandr --verbose | grep -i brightness | awk 'NR==1{print $2}') \* 100 | bc -l | xargs printf "%.0f\n")
if [[ ${oldBri} -eq 0 ]]; then
  xrandr --output eDP1 --brightness 0.35 && pkill -RTMIN+1 i3blocks
else
  xrandr --output eDP1 --brightness 0 && pkill -RTMIN+1 i3blocks
fi

